### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by ghost** [ewhitesides/pulp_operations#6]
Could you, after your changes and rewrite of certain parts, create a release / tag?

Im asking because currently i use this to use the latest stable:
`git+https://github.com/ewhitesides/pulp_operations.git@abadca1fa75bf2f7118b7ed6da9eaf042cf204a6`

**Comment by ewhitesides** [comment]
i set so we start at version 1.0 which is the latest one.  i added several scripts that i didn't have published before.
